on: push
name: build website every push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - uses: octokit/request-action@v2.x
      id: get_all_releases
      with:
        route: GET /repos/{owner}/{repo}/releases
        owner: OliBomby
        repo: Mapping_Tools
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - run: |
        cat >all_releases.json <<- EOF
        ${{ steps.get_all_releases.outputs.data }}
        EOF

    - uses: octokit/request-action@v2.x
      id: get_latest_release
      with:
        route: GET /repos/{owner}/{repo}/releases/latest
        owner: OliBomby
        repo: Mapping_Tools
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - run: |
        cat >latest_release.json <<- EOF
        ${{ steps.get_latest_release.outputs.data }}
        EOF

    - name: download zola
      run: curl -L https://github.com/getzola/zola/releases/download/v0.10.1/zola-v0.10.1-x86_64-unknown-linux-gnu.tar.gz > zola.tar.gz

    - name: unpack zola
      run: tar -xzf zola.tar.gz

    - name: copy-release-info
      run: |
        cp all_releases.json website
        cp latest_release.json website

    - name: build
      run: ./zola --root website build -u https://olibomby.github.io/Mapping_Tools -o build

    - name: copy-release-info
      run: |
        cp all_releases.json build
        cp latest_release.json build

    - name: deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build

